# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U188vlxtwOFkXeX6FfjCwwYLNU2_AOGS
"""

from setuptools import setup

setup(name='PIP',
      version='0.0.1',
      url="https://github.com/Gaianeve/gym-PIP",
      author="Gaia Bartoli",
      install_requires=install_requires=["gym==0.25.2", "numpy==1.23.5", "pybullet==3.2.6", "GitPython==3.1.43"],
)